validated through deployment.json

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -10,7 +10,6 @@ on:
 jobs:
   deploy:
     runs-on: ubuntu-latest
-
     steps:
       - name: Checkout Code
         uses: actions/checkout@v3
@@ -23,139 +22,84 @@ jobs:
       - name: Login to Azure
         run: |
           az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
-          # Check if service principal exists
-          az ad sp show --id ${{ secrets.AZURE_CLIENT_ID }}
 
       - name: Install Bicep CLI
         run: az bicep install
 
-      - name: Generate Unique Solution Prefix and Environment Name
+      - name: Generate Resource Group Name
+        id: generate_rg_name
+        run: |
+          echo "Generating a unique resource group name..."
+          TIMESTAMP=$(date +%Y%m%d%H%M%S)
+          COMMON_PART="pslautomationRes"
+          UNIQUE_RG_NAME="${COMMON_PART}${TIMESTAMP}"
+          echo "RESOURCE_GROUP_NAME=${UNIQUE_RG_NAME}" >> $GITHUB_ENV
+          echo "Generated Resource_GROUP_PREFIX: ${UNIQUE_RG_NAME}" 
+      
+      - name: Check and Create Resource Group
+        id: check_create_rg
+        run: |
+          set -e  
+          echo "Checking if resource group exists..."
+          rg_exists=$(az group exists --name ${{ env.RESOURCE_GROUP_NAME }})
+          if [ "$rg_exists" = "false" ]; then
+            echo "Resource group does not exist. Creating..."
+            az group create --name ${{ env.RESOURCE_GROUP_NAME }} --location northcentralus || { echo "Error creating resource group"; exit 1; }
+          else
+            echo "Resource group already exists."
+          fi
+
+      - name: Generate Unique Solution Prefix
         id: generate_solution_prefix
         run: |
           set -e
-          COMMON_PART="pslc"
+          COMMON_PART="pslr"
           TIMESTAMP=$(date +%s)  
           UPDATED_TIMESTAMP=$(echo $TIMESTAMP | tail -c 3) 
           UNIQUE_SOLUTION_PREFIX="${COMMON_PART}${UPDATED_TIMESTAMP}"
-          ENVIRONMENT_NAME="env-${UNIQUE_SOLUTION_PREFIX}"  # Dynamically generated environment name
           echo "SOLUTION_PREFIX=${UNIQUE_SOLUTION_PREFIX}" >> $GITHUB_ENV
-          echo "ENVIRONMENT_NAME=${ENVIRONMENT_NAME}" >> $GITHUB_ENV
-          echo "Generated SOLUTION_PREFIX: ${UNIQUE_SOLUTION_PREFIX}, ENVIRONMENT_NAME: ${ENVIRONMENT_NAME}"
+          echo "Generated SOLUTION_PREFIX: ${UNIQUE_SOLUTION_PREFIX}" 
 
-      - name: Deploy Bicep Template at Subscription Level
+      - name: Deploy Bicep Template
         id: deploy
         run: |
           set -e
-          echo "Deploying bicep template at the subscription level...."
-          deployment_output=$(az deployment sub create \
-            --location WestUS \
-            --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} \
-            --template-file infra/main.bicep \
+          az deployment group create \
+            --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
+            --template-file infrastructure/deployment.json \
             --parameters \
-                authClientId=${{ secrets.AZURE_CLIENT_ID }} \
-                authClientSecret=${{ secrets.AZURE_CLIENT_SECRET }} \
-                environmentName=${{ env.ENVIRONMENT_NAME }} \
-                location=NorthCentralUS \
-                principalId=${{ secrets.AZURE_PRINCIPAL_ID }} \
-            --query "properties.outputs.webappName.value" --output json)
+                HostingPlanName="${{ env.SOLUTION_PREFIX }}-plan" \
+                ApplicationInsightsName="appins-${{ env.SOLUTION_PREFIX }}" \
+                WebsiteName="webapp-${{ env.SOLUTION_PREFIX }}" \
+                CosmosDBName="db-cosmos-${{ env.SOLUTION_PREFIX }}" \
+                CosmosDBRegion="NorthCentralUS" \
+                AzureSearchService="search-${{ env.SOLUTION_PREFIX }}" \
+                AzureOpenAIResource="aoai-${{ env.SOLUTION_PREFIX }}" \
+                WorkspaceName="worksp-${{ env.SOLUTION_PREFIX }}" 
 
-          # Extract the webapp name from JSON response using jq
-          webapp_name=$(echo $deployment_output | jq -r .)
-          echo "webapp_name=$webapp_name" >> $GITHUB_ENV
-          echo "Deployment completed with webapp_name: $webapp_name"
-
-      - name: Update Web App Docker Configuration
+      - name: Wait for Resource Deletion to Complete
         run: |
-          set -e
-          echo "Updating the Web App to use the ACR Docker image..."
-          
-          # Use the dynamically retrieved web app name from the deployment step
-          webapp_name=${{ env.webapp_name }}
-          container_registry="byocgacontainerreg.azurecr.io"
-          image_name="webapp:dev"
-        
-          # Set up Web App with the correct ACR image
-          az webapp config container set \
-            --name $webapp_name \
-            --resource-group rg-${{ env.ENVIRONMENT_NAME }} \
-            --docker-custom-image-name "$container_registry/$image_name" \
-            --docker-registry-server-url "https://$container_registry" \
-            --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} \
-            --query "containerSettings" \
-            --output json
-
-      - name: List KeyVaults and Store in Array
-        id: list_keyvaults
-        run: |
-          set -e
-          echo "Listing all KeyVaults in the subscription..."
-          
-          # Get the list of KeyVaults in the subscription
-          keyvaults=$(az resource list --resource-type "Microsoft.KeyVault/vaults" --query "[].name" -o tsv)
-
-          if [ -z "$keyvaults" ]; then
-            echo "No KeyVaults found in the subscription."
-            echo "KEYVAULTS=[]" >> $GITHUB_ENV  # If no KeyVaults found, set an empty array
-          else
-            echo "KeyVaults found: $keyvaults"
-
-            # Format the list into an array with proper formatting (no trailing comma)
-            keyvault_array="[" 
-            first=true
-            for kv in $keyvaults; do
-              if [ "$first" = true ]; then
-                keyvault_array="$keyvault_array\"$kv\""
-                first=false
-              else
-                keyvault_array="$keyvault_array,\"$kv\""
-              fi
-            done
-            keyvault_array="$keyvault_array]"
-
-            # Output the formatted array and save it to the environment variable
-            echo "KEYVAULTS=$keyvault_array" >> $GITHUB_ENV
-          fi
-      
-      - name: Delete Bicep Deployment
-        if: success()
-        run: |
-          set -e
-          echo "Deleting the resources from the subscription..."
-          az deployment sub delete \
-            --name rg-${{ env.ENVIRONMENT_NAME }} \
-            --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} \
-            --no-wait
-
-      - name: Wait for resource deletion to complete
-        run: |
-          # List of KeyVaults and additional resources
-          KEYVAULTS="${{ env.KEYVAULTS }}"
-
-          # Remove the surrounding square brackets, if they exist
-          stripped_keyvaults=$(echo "$KEYVAULTS" | sed 's/\[\|\]//g')
-          
-          # Convert the comma-separated string into an array
-          IFS=',' read -r -a resources_to_check <<< "$stripped_keyvaults"
-          
-          # Append new resources to the array
-          resources_to_check+=("${{ env.SOLUTION_PREFIX }}-openai" "${{ env.SOLUTION_PREFIX }}-cogser")
-
-          echo "List of resources to check: ${resources_to_check[@]}"
+          # List of resources to check based on SOLUTION_PREFIX
+          resources_to_check=(
+            "aoai-${{ env.SOLUTION_PREFIX }}"
+            "appins-${{ env.SOLUTION_PREFIX }}"
+            "db-cosmos-${{ env.SOLUTION_PREFIX }}"
+            "${{ env.SOLUTION_PREFIX }}-plan"
+            "search-${{ env.SOLUTION_PREFIX }}"
+            "webapp-${{ env.SOLUTION_PREFIX }}"
+            "worksp-${{ env.SOLUTION_PREFIX }}"
+          )
 
           # Get the list of resources in YAML format
           resource_list=$(az resource list --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} --output yaml)
-
-          # Maximum number of retries
+          
+          # Maximum number of retries and retry intervals
           max_retries=3
-
-          # Retry intervals in seconds (30, 60, 120)
           retry_intervals=(30 60 120)
-
-          # Retry mechanism to check resources
           retries=0
+          
           while true; do
             resource_found=false
-
             # Iterate through the resources to check
             for resource in "${resources_to_check[@]}"; do
               echo "Checking resource: $resource"
@@ -174,7 +118,6 @@ jobs:
                 echo "Maximum retry attempts reached. Exiting."
                 break
               else
-                # Wait for the appropriate interval for the current retry
                 echo "Waiting for ${retry_intervals[$retries-1]} seconds before retrying..."
                 sleep ${retry_intervals[$retries-1]}
               fi
@@ -187,72 +130,61 @@ jobs:
       - name: Purging the Resources
         if: success()
         run: |
-          set -e 
-          # Define variables
-          OPENAI_COMMON_PART="-openai"
-          openai_name="${{ env.SOLUTION_PREFIX }}${OPENAI_COMMON_PART}"
-          echo "Azure OpenAI: $openai_name"
+          set -e
+          # Purging resources based on solution prefix
+          echo "Purging resources..."
 
-          MULTISERVICE_COMMON_PART="-cogser"
-          multiservice_account_name="${{ env.SOLUTION_PREFIX }}${MULTISERVICE_COMMON_PART}"
-          echo "Azure MultiService Account: $multiservice_account_name"
-
-          # Purge OpenAI Resource
-          echo "Purging the OpenAI Resource..."
-          if ! az resource delete --ids /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/providers/Microsoft.CognitiveServices/locations/uksouth/deletedAccounts/$openai_name --verbose; then
-            echo "Failed to purge openai resource: $openai_name"
-          else
-            echo "Purged the openai resource: $openai_name"
-          fi
-   
-          # Purge MultiService Account Resource
-          echo "Purging the MultiService Account Resource..."
-          if ! az resource delete --ids /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/providers/Microsoft.CognitiveServices/locations/uksouth/deletedAccounts/$multiservice_account_name --verbose; then
-            echo "Failed to purge multiService account resource: $multiservice_account_name"
-          else
-            echo "Purged the multiService account resource: $multiservice_account_name"
-          fi
-
-          # Ensure KEYVAULTS is properly formatted as a comma-separated string
-          KEYVAULTS="${{ env.KEYVAULTS }}"
-
-          # Remove the surrounding square brackets, if they exist
-          stripped_keyvaults=$(echo "$KEYVAULTS" | sed 's/\[\|\]//g')
+          # List of resources to purge
+          resources_to_purge=(
+            "aoai-${{ env.SOLUTION_PREFIX }}"
+            "appins-${{ env.SOLUTION_PREFIX }}"
+            "db-cosmos-${{ env.SOLUTION_PREFIX }}"
+            "${{ env.SOLUTION_PREFIX }}-plan"
+            "search-${{ env.SOLUTION_PREFIX }}"
+            "webapp-${{ env.SOLUTION_PREFIX }}"
+            "worksp-${{ env.SOLUTION_PREFIX }}"
+          )
           
-          # Convert the comma-separated string into an array
-          IFS=',' read -r -a keyvault_array <<< "$stripped_keyvaults"
-
-          echo "Using KeyVaults Array..."
-          for keyvault_name in "${keyvault_array[@]}"; do
-            echo "Processing KeyVault: $keyvault_name"
-            # Check if the KeyVault is soft-deleted
-            deleted_vaults=$(az keyvault list-deleted --query "[?name=='$keyvault_name']" -o json --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }})
-
-            # If the KeyVault is found in the soft-deleted state, purge it
-            if [ "$(echo "$deleted_vaults" | jq length)" -gt 0 ]; then
-              echo "KeyVault '$keyvault_name' is soft-deleted. Proceeding to purge..."
-              az keyvault purge --name "$keyvault_name" --no-wait
+          for resource in "${resources_to_purge[@]}"; do
+            echo "Purging resource: $resource"
+            if ! az resource delete --ids /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/providers/Microsoft.CognitiveServices/locations/uksouth/deletedAccounts/$resource --verbose; then
+              echo "Failed to purge resource: $resource"
             else
-              echo "KeyVault '$keyvault_name' is not soft-deleted. No action taken."
+              echo "Purged the resource: $resource"
             fi
           done
 
           echo "Resource purging completed successfully"
-      
+
+      - name: Delete Bicep Deployment
+        if: success()
+        run: |
+          set -e  
+          echo "Checking if resource group exists..."
+          rg_exists=$(az group exists --name ${{ env.RESOURCE_GROUP_NAME }})
+          if [ "$rg_exists" = "true" ]; then
+            echo "Resource group exists. Cleaning..."
+            az group delete \
+                --name ${{ env.RESOURCE_GROUP_NAME }} \
+                --yes \
+                --no-wait
+            echo "Resource group deleted...  ${{ env.RESOURCE_GROUP_NAME }}"
+          else
+            echo "Resource group does not exist."
+          fi
+
       - name: Send Notification on Failure
         if: failure()
         run: |
           RUN_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
-      
-          # Construct the email body
+
           EMAIL_BODY=$(cat <<EOF
           {
-            "body": "<p>Dear Team,</p><p>We would like to inform you that the Client Advisor Automation process has encountered an issue and has failed to complete successfully.</p><p><strong>Build URL:</strong> ${RUN_URL}<br> ${OUTPUT}</p><p>Please investigate the matter at your earliest convenience.</p><p>Best regards,<br>Your Automation Team</p>"
+            "body": "<p>Dear Team,</p><p>We would like to inform you that the Research Assistant Automation process has encountered an issue and has failed to complete successfully.</p><p><strong>Build URL:</strong> ${RUN_URL}<br> ${OUTPUT}</p><p>Please investigate the matter at your earliest convenience.</p><p>Best regards,<br>Your Automation Team</p>"
           }
           EOF
           )
-      
-          # Send the notification
+
           curl -X POST "${{ secrets.LOGIC_APP_URL }}" \
             -H "Content-Type: application/json" \
             -d "$EMAIL_BODY" || echo "Failed to send notification"
